
"""
Goal here- To create a working Mulit-Agent System that can handle these tasks effectively end to end:

1) Research Agent - The research agent is responsible for handling the development of portfolio company leads within the CIC and broader Boston ecosystem


2) Validation Agent - The validation agent checks the work of the research agent to ensure the output is accurate and reliable. It flags hallucinated facts, portfolio companies that don't exist, and companies that aren't located in the Greater Boston area


3) Research Analyst Translator- The research analyst translator will sit between the research, validation agents, and the Director agent handling the physical translation and synthesis of information to both sides. They also have responsibility for 


4) Director - The director synthesizes the research findings, identifies the overlaps across different research sources, and creates a detailed executive brief

5) Executive Agent - The executives makes the final judgement call of which companies are most likely inside the desired portfolio circle

System-Wide Questions:
-> Who owns observability, and how can it be centralized?
-> What guardrails need to be in place to prevent an agent from going rogue?

PROJECT EXECUTION PLAN-
1) Build a tiny single agent end-end system 

*Initial Iteration Results Documented
-> Current system designed with a single agent and a single task. However, the single agent has an ultra specific goal or mandate to solve. The task itself however has multiple steps. The agent has to complete the following steps:
Navigate to each website, identify portfolio companies associated with each firm, and document the names. Loop back to the initial list go down to the next entry and repeat. Expected output is also hyper specific and specifies a clear markdown file with 3 columns

-> Token Economics
Prompt Tokens- 2,282
Reasoning Tokens- 0
Completion Tokens- 3,469
Total Token Usage Details- 5,751

-> Latency/Performance Metrics (By Step)
Cumulative Breakdown:
    Total Execution Time (3 runs) - 530 - 600 seconds total
    Task Execution Planner - 261.2 seconds
    Prefill Tokens - 5.1 seconds
    Creating Reasoning Plan - 12.8 seconds
    Compose LLM call to test reasoning plan- 142.6 seconds
    Generate Output/Completion Tokens- 131.4 seconds

Tracking at Task Level:
a) Planning/Reasoning - ~261.1 seconds
-Build initial planning and reasoning- ~256 seconds
-Prefill Tokens- ~5.1 seconds

c) Generate Response- ~274.0 seconds
-Execute Planning Task - ~142.6 seconds
-Generate Final Output/Response- ~131.4 seconds

Tracking Token Usage and Expansion by Steps:
-Standard task planning prompt (generated by Ollama) - 261 tokens
-User Prompt - 4,118 tokens
-UsageInputTokens- 911
-MessageSize- 7,315 tokens

-UsageOutputTokens- 1,661 tokens
-Generates instructions for LLM totalling 7,071 tokens
-Generates output back to the user totalling 2,710 tokens
Input Message Tokens (Task Description)- 1,342 tokens
Input Message Tokens (Expected Output) - 531 tokens
Input Message Tokens (Backstory) - 294 tokens
Message to LLM for execution planning - 2,517 tokens
Plan Returned for execution planning - 3, 101 tokens 

-> Accuracy and Reliability Details
-Agent failed to produce any relevant content to populate the markdown document. Instead this just created a shell of the 3 columns
-Reveals a critical gap in Telemetry and Performance/Memory/CPU/VRAM monitoring. Using tracing=True only covers application level details NOT system or infra level details

->Options for implementing proper Telemetry- 
A) Integrate Memory/CPU tools such psutil, cprofile, and tracemalloc directly into the application logic. 
B) Tracing system level tracking at the Ollama Server level - requires running application in seperate terminal window
C) Integrate OpenTelemetry for stack-level tracing and system-level logging
D) Integrate Phoenix, Langfuse, and others

2) Preliminary Conclusions:
-> ~80% of the execution runtime is dominated by the planning phase of the task. The actual execution of the task only occupies ~20% of total runtime
-> Input tokens are significantly higher than expected, not catastrophic but usage/consumption is certainly higher than anticipated
-> Agent does not return a useable output just a skeleton for a table - WHY? Suspect this has much to do with the amount of tokens being used we have nearly filled the context window


*Measuring Input/Output Tokesn Breakdown by Task:
A) Input Tokens
-Standard Planning template- 261
-Backstory- 294
-Description- 1,342
-Expected Output- 531


C) Characters and Tokens by Task Stage (Input vs. Output Tokens Breakdown)- Approximation 
-Input Message (System) - 261 characters
-Input Message (User) - 4,148 characters
-Call the LLM - OUTPUT Message - 7,071 characters
-Passed to Agent in LLM call 
-> Input Message (1,342 characters total)
-> Output Message (2,710 characters total)
-Agent Execution
-> Backstory (294 characters total)
-> Task Description (1,342 characters)
-> Expected Output (531 characters)

-LLM Call Response
-> Input Messages (2,517 characters)
-> Output Messages (3,447 characters)

*Execute plan
-Function call (3,101 characters)

*Returning Output
-Input Messages (System) - 482 characters
-Input Messages (User) - 2,056 characters
-Output Message (User) - 2,710 characters

Conclusions and Next Steps:
-> Latency and Performace- Strip both planning and reasoning modes out - Drop response times from 530-600 seconds to <180 seconds. This is a fairly strong performance improvement. BUT we lose something- the ability to reason and plan for more complex tasks
-> Token Usage and Economics- stripping both planning and reasoning modes out- Dropped token usage from ~5,800 tokens -> ~1,600 tokens. 
Hypothesis: Modularizing the one big task into different smaller tasks would likely improve reliability and accuracy?

* Planning Guardrails for next evolution
1) Enforced guardrail to ensure the model returns content
2) Enforced guardrail to ensure the model doesn't just parrot the schema
3) Enforced guardrail to ensure the model returns companies that actually exist rather than making up entries

*Whether or not to enforce Structured Input/Output Format- 

*How to balance reliability with token usage - Put a small classifier in front of the workflow to classify the difficulty of the proposed task before executing it
-> Push compute and resource intensive reasoning and planning to back-end queues or similar asynchronous design

*What happens when we expand the number of target firms from 6 to 12 or doubles again to 24?-
-> Far more likely to hallucinate or produce an incomplete result - Fixing the risk of hallucinations required a clearer prompt and careful rewording (i.e. this might be brittle) - BUT while the output wasn't perfect, it was usable and we reduced latency from 530-600 seconds -> 150-180 seconds by cutting planning and reasoning modes
-> We observe tail latency could be as high as 330 seconds

*The pros and cons of what we have accomplished thus far:
-We have a working end-end agent that works, and runs significantly and more efficiently than it did initially. We successfully cut latency by ~50-70% in the first pass, and we successfully cut token usage by ~50-60%
-Imperfections- the end to end process is brittle and sometimes the LLM returns incomplete results or fails to follow instructions. Furthermore, we observe that the LLM tends to name the exact same portfolio companies consistently across the spectrum (likely because we set temperature to 0)

*Hypothesis - If we raise temperature from 0 to 0.2 we will induce additional entries in the list- Need to carefully watch hallucination rates and frequency as we raise temperature - Hallucinated later entries twice and the third time completely hallucinated
-> Test reduce the list back down to 6 entries- keep temperature as is - re-run 3x and observe hallucination rates
-> Raising temperature to 0.5;


3) NEXT STEPS AND FOCUS AREAS:
-Revise 'all or nothing' reasoning and planning approach - Put a small classifier in front of the LLM and use this to classify the difficulty of the task. Investigate how difficulty ratings correlate to LLM output results based on telemetry.
-Develop guardrails for incorrect information returned, incomplete outputs, and prompt mimicking
-Determine whether or not to introduce Structured Input and Structured Output Formats - Pros: Better schema discipline, much fewer formatting errors; Cons- More token spend
-Determine and judge severity of errors from LLM - we are going to have to distingush between catastrophic vs. high impact vs. nuisance mistakes. Perhaps, we create a severity score for hallucinations or a similar methodology
-Create error codes to handle errors returned from the LLM ?

*Practical Implementation Questions:
-How do we verify the output format is correct - Pydantic (high brittleness when using small language models and complex tasks)
-How do we verify the output format is complete- Some sort of check or constraint that checks for missing or empty entries
-How do we verify a portfolio company exists - We need some sort of primary source to handle this (Secertary of State Websites)
-How do we verify a portfolio company hasn't been acquired, winded down, dissolved, or transferred? - Much harder, relying on SEC Edgar and Recent Company News
-How do we verify the funding stage for each investment fund into a portfolio company?- Crunchbase, Recent Company News, Filings. Crunchbase costs actual money so that might be a major issue
-How do we verify the portfolio company is affiliated with CIC? - This is where things break down and we actually need multiple steps to triangulate this

-When we restore planning and reasoning- What problems actually need it and why? What is the common denominator between these entries, tasks, steps, or workflows? Can we find a latency efficient way to handle these demands?







"""




#Import Required Modules
from crewai import Agent, Task, Crew, Process, LLM
OLLAMA_BASE_URL = "http://localhost:11434"

import time
import psutil #Implement performance monitoring / observability basics



#This is not state safe, re-runs on each script load
perf_details = {}


"""
Benchmark Measurement Agent
-> Classify task difficulty
-> Classify risk of hallucinations
-> Classify severity of mistakes
-> Difficulty navigating website for agents, web scrapers, etc..
-> 


Alternative: Try Jev to do this if we have trouble with agents
Alternative 2: Standard ML Classification algorithm
"""


##### GuardRails ####

#Security- Scan prompt for prompt injection risk
def scan_prompt():
    pass

#Reliability- Scan output to ensure the agent produced useful work
def verify_output():
    pass

#Define the base large language model call
base_llm_model_settings= LLM(
    model= 'ollama/llama3.2:latest',
    base_url=OLLAMA_BASE_URL,
    api_key='ollama',
    temperature=0
)


benchmark_complexity_agent = Agent(
    role = 'Risk Assessment Director', 
    goal='Classify the difficulty of the task below into either Easy, Medium, or Hard.',
    backstory='You are an experienced risk director with 20 years of experiencing weighting qualitative and quantitative data to identify risk proactively. Your job is to classify the different tasks in the workflow based on the risk assessment. Your job is not to produce the requested information.',
    max_tokens=300,
    num_context=8192,
    llm=base_llm_model_settings,
    tracing=True,
    verbose=True,
    keep_alive=True
)

classify_task_difficulty = Task(
    agent=benchmark_complexity_agent,
    description="""
    
            Go through the list of Boston-based VC funds, shown here: {inputs}. Navigate to each website and identify which portfolio companies they have invested in from the website.
            The exact location of this information on each website may be very different, use your expert judgement and reasoning skills to navigate the website effectively.
        
                    """,
    
        expected_output="""A classification decision on how difficult it would be to identify the requested information from the websites.",
        The classification decision should contain a clear chain of reasoning and logic - and a clear classification of difficulty into either easy, medium, or hard"""
)

classify_available_info = Task(
    agent = benchmark_complexity_agent,
    description="""
                Go to each website and classify how much information regarding portfolio companies and details are on the website- your classification should
                fall under either low, medium, or high
                """,
    expected_output="""
                    A summary containing each website and an assessment of information availability on portfolio companies - low, medium, or high
                    """
)


classify_website_navigation= Task(
    agent=benchmark_complexity_agent,
    description="""
                Go through the list of Boston-based VC funds, shown here: {inputs}. Navigate to each website and identify which portfolio companies they have invested in from the website.
                            The exact location of this information on each website may be very different, use your expert judgement and reasoning skills to navigate the website effectively.
                        
                

                """,

    expected_output="""
                    After going through each funds website, classify the ease of navigation for both a machine and a human reviewer.
                    The classification decision should include a decision of easy, medium, or hard for both audiences and each fund.
                    If you cannot complete the request, please tell me if you could complete the request if you were given a virtual browser tool or web search.
                    """

)

classify_expected_request_time = Task(
    agent=benchmark_complexity_agent,
        description="""
                    Go through the list of Boston-based VC funds, shown here: {inputs}. Navigate to each website and identify which portfolio companies they have invested in from the website.
                                The exact location of this information on each website may be very different, use your expert judgement and reasoning skills to navigate the website effectively.
                            
                    
    
                    """,
    
        expected_output="""
                        Based on the number of entries in the list, and anticipated difficulty of the task, please classify the expected request latency into one of the following buckets-
                        - < 120 seconds
                        - 120 - 240 seconds
                        - > 240 seconds
                        
                        Please include a brief explanation of reasoning, chain of logic and thinking.
                        """
    
)












research_agent = Agent(
    role='Research Analyst',

    goal='Identify portfolio companies of the listed VC firms that are highly likely to be affiliated with the Cambridge Innovation Center Ecosystem',

    backstory='You are a highly experienced researcher who knows how to triangulate a signal from disparate sources to uncover novel and meaningful information. You have 20 years of experience working within the startup ecosystem and have an intimate understanding of the Cambridge Innovation Center Ecosystem',

    #reasoning=True, #Remove reasoning requirement
    llm = base_llm_model_settings,
    #max_tokens=300,
    max_reasoning_attempts=3, #Cap revisions to the plan from this agent at 3
    num_ctx = 8192,
    keep_alive=True, #Keep this thread alive throughout the running process,
    tracing = True,
    verbose=True
    )

task1 = Task(
    description="""

        Go through the list of Boston-based VC funds, shown here: {inputs}. Navigate to each website and identify which portfolio companies they have invested in from the website.
        The exact location of this information on each website may be very different, use your expert judgement and reasoning skills to navigate the website effectively.
    
                """,

    expected_output="""A neatly formatted comprehensive table listing each portfolio company, what VC fund invested in each company, and at what funding stage.  \
    The final output should be a comprehensive markdown document containing 3 columns-

        -Portfolio Company Name
        -VC or Investment Fund investing in portfolio company
        -The stage in which the VC or investment fund invested in each portfolio company name

        For each investment fund included in the inputs shown again here: {inputs} please return exactly 5 portfolio companies the fund has invested in with a preference towards finding early stage companies. If you are unable to identify 5 portfolio companies for a given fund, please note that you could not locate any other names rather than making up companies.
        It is imperative that each row in the table be fully filled out and complete prior to returning a result, partial result returns will crash the program!

        """,
    
    agent = research_agent,
    tracing=True,
    verbose=True
    )



#Build and Assemble the crew to perform the task
crew = Crew(
    agents=[benchmark_complexity_agent],
    tasks=[classify_task_difficulty, classify_available_info, classify_website_navigation, classify_expected_request_time],
    #agents = [research_agent],
    #tasks=[task1],
    #planning=True, #Create a plan before executing anything
    #Route planning through ollama
    #planning_llm= base_llm_model_settings,
    process=Process.sequential,
    verbose=True,
    tracing=True
)

#SET UP PSUTIL MEMORY AND COMPUTE TRACKING
process = psutil.Process()
print("--- Starting Execution Trace & Resource Audit ---")
start_time = time.time() #Set the start time

start_memory_mb = process.memory_info().rss/ (1024 * 1024)


#Kick off the Agentic Crew
try:

    crew_results = crew.kickoff(
        {
            'inputs': [
                'Flagship Pioneering',
                'Third Rock Ventures',
                'RA Capital Management',
                'SV Health Investors',
                'Bain Capital Ventures',
                'Spark Capital',
                'Flybridge Capital Partners',
                'Glasswing Ventures',
                'Bessemer Ventures'
                #'Clean Energy Ventures',
                #'T1D Fund',
                #'Progress Ventures',
                #'Boston Millenia Partners',
                #'Branch Venture Group',
                #'Greenlight Fund',
                #'Streetlight Ventures',
                #'C10Labs',
                #'TiE Boston Angels',
                #'Sidecar Angels',
                #'Dreavent Capital',
                #'J2 Ventures',
                #'One Way Ventures'
                ]
        }
    )

    #View results down here
    print(f"Raw Output: {crew_results.raw}")
    print(f"Prompt Token Details: {crew_results.token_usage.prompt_tokens}")
    print(f"Reasoning Token Details: {crew_results.token_usage.reasoning_tokens}")
    print(f"Completion Token Details: {crew_results.token_usage.completion_tokens}")
    print(f" Total Token Usage Details: {crew_results.token_usage.total_tokens}")


except Exception as e:
    pass


finally:
    end_time = time.time() #Record the ending time for execution 
    final_memory_mb = process.memory_info().rss/ (1024 * 1024)
    cpu_usage_pct = process.cpu_percent(interval=None)

    print("\n--- Performance & Resource Summary ---")
    print(f"Total Execution Time: {end_time - start_time:.2f} seconds")
    print(f"RAM Footprint Start: {start_memory_mb:.2f} MB")
    print(f"RAM Footprint End:   {final_memory_mb:.2f} MB (Delta: {final_memory_mb - start_memory_mb:+.2f} MB)")
    print(f"Process CPU Usage:   {cpu_usage_pct}%")
















